### ISSUE TITLE
Add data source info to data

### ISSUE THREAD

**Issue by ka7eh** [Oceans-1876/challenger-data#3]
We should create a json file (`data_source.json`) in `Oceans1876` that contains details of data sources used by gnverifier (see https://github.com/gnames/gnverifier/ and http://resolver.globalnames.org/data_sources).

For now, the main things to include are id and title as seen in the link above, and a URL template that accepts a species id and it takes users to that species page on that data source. If you notice other useful attributes for data sources, feel free to include them.

For example, Catalogue of Life URL template is like this: `https://www.catalogueoflife.org/data/taxon/${species_id}`.
So for the "Hymenaster membranaceus" (id: 3NHT8) that is fetched from this data source, we go see its details at https://www.catalogueoflife.org/data/taxon/3NHT8.

This is probably a manual task because each data source is different and the list is small and limited.

We can then use this new json file to populate the data source table in the API.

**Comment by Rashmil-1999** [comment]
I first got the json response from the api used by `gnverifier` for `dataSource`, which was a bit inconsistent. I then restructured it to have exact same fields. Now when I was visiting each data-source pages, I found out that not all the websites reference the species via their `recordId`. So for example, Catalogue of Life uses the `recordId` in the URL to locate a particular species resource. While data source such as `Wikimedia`/`Wikispecies` don't, what it does is basically, uses the species name joined via `_` and capital letters preserved.

This might cause a problem when we try to feed id to the URL dynamically. If this is only for this datasource, then we can move ahead with some custom logic while we build the response but otherwise this could seem like an issue.

For the time being I am just adding `${species_id}` for every resource I can find and noting down which one is an aberrant one.
